### ISSUE TITLE
[New build - EXPERIMENTAL] 20w41b: Blueprint hotfix.

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#3044]
A quick fix for the blueprint regression.

Improvements:
- Reset to Default keybind button.

Bugfixes:
#3039 #3042 Cannot load any blueprint
Turret hinge will jump to -90 when first activated.

**Comment by SnowyBirdot** [comment]
Didn't even have time to file a bug report, good job Tsuna!

**Comment by tsunamayo** [comment]
Build is up! hopefully the turret bug is fixed also...

**Comment by Dwarf-LordPangolin** [comment]
The blueprint bug still seems to be hanging around, but the turret bug looks fixed!

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin could you please send me log? thx

**Comment by Dwarf-LordPangolin** [comment]
Sure thing; here it is.

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5338497/output_log.txt)

**Comment by tsunamayo** [comment]
@Dwarf-LordPangolin okay I just pushed a new build, if you can tell me how it is, and also send me the log even if it work! cheers

**Comment by Dwarf-LordPangolin** [comment]
You did it! :grinning: Working fine. Here's the 20w41c log:

[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5338602/output_log.txt)

**Comment by tsunamayo** [comment]
so you have a space at the end of this bp: "Mistral Grav Drive ". That was the culprit, I will add a few line check to make sure no space is input at the end of the name. It cause issues for workshop upload too!
Cheers

**Comment by Dwarf-LordPangolin** [comment]
Good to know; thanks!
