### ISSUE TITLE
The more you use interstellar travel the more unstable the game becomes until you relog

### ISSUE THREAD

**Issue by amplified1** [tsunamayo/Starship-EVO#3223]
it is basically impossible to do 2 consecutive long-range warps because of how unstable it becomes, is it going to still be like this when it leaves experimental?

**Comment by amplified1** [comment]
Collisions start to not work and the game starts to run at 1 frame a second

**Comment by tsunamayo** [comment]
Hi, as usual could you send the output.log? Thanks

**Comment by ProPeach** [comment]
I just checked this myself, and I was able to jump 5 times without any issues. However, the moment I initiated Lightcruise in the 5th system, my frames dropped from 60 to 7-3
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5541647/output_log.txt)

![image](https://user-images.githubusercontent.com/27857711/99160114-a0a82700-26db-11eb-8616-1d101c6457f7.png)

**Comment by tsunamayo** [comment]
I see interesting test case, I will keep you guys posted.

**Comment by amplified1** [comment]
I would send my output log but the file has become to large to directly upload

**Comment by amplified1** [comment]
it definitely seems like the instability is caused by distance, as a bunch of small warps aren't a huge issue but 2-3 warps of ~30 LY is an issue

**Comment by tsunamayo** [comment]
Fixed in 20w47a. Build uploaded soon!

**Comment by ProPeach** [comment]
I'm still experiencing this issue in 20w47a, although this time the frame dropped to 0 when I came *out* of Lightcruise after travelling 60Ls in 3 different jumps.
![image](https://user-images.githubusercontent.com/27857711/99587915-bff7ca80-29e1-11eb-9d8c-65ba191e2ebf.png)
[output_log.txt](https://github.com/tsunamayo/Starship-EVO/files/5562720/output_log.txt)

**Comment by tsunamayo** [comment]
Okay hopefully it should be fixed now, dont hesitate to ping me again if not! It is all a bit random, it is when you warp fast in succession, the engine have to dispose of ship that are still being spawned, which can break the game if I didnt made the  correct checks.
