### ISSUE TITLE
screen shaking and more.

### ISSUE THREAD

**Issue by luvexis** [tsunamayo/Starship-EVO#3340]
### Short Description of the issue:

... whenever near a structure or just walking around the screen shakes and my character seems to move around. makes the game almost completely unplayable. can not enter the tutorial building because of it.

### Steps to reproduce the issue:
walk around causes the screen to shake like crazy. causes ships to shake and move around. can glitch me through blocks as well
...

### Environment
- Starship EVO version: 
- Graphics Card: nvidia GeForce GTX 745

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `output_log.txt` file. You can find your log here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`

**Comment by tsunamayo** [comment]
Issue is fixed in 20w49a. This was the experimental build, I am pushing this as the main build now. Thanks

**Comment by luvexis** [comment]
if its fixed why is it still happening?

**Comment by luvexis** [comment]
> Issue is fixed in 20w49a. This was the experimental build, I am pushing this as the main build now. Thanks

why am I still having the issue then? also, every block I place is now invisible.

**Comment by tsunamayo** [comment]
You are using the default branch, the fix was in the experimental beta branch. This is why we ask in the bug report to see which version you used. Now the fix is in Default, you can retry. Thanks

**Comment by luvexis** [comment]
o

> You are using the default branch, the fix was in the experimental beta branch. This is why we ask in the bug report to see which version you used. Now the fix is in Default, you can retry. Thanks

ok thats on me sorry. im being a total bother here but how do i get to the experimental beta branch? again im sorry for being a massive pain.....
