### ISSUE TITLE
[New build - EXPERIMENTAL] 21w24a: Build Option Menu 

### ISSUE THREAD

**Issue by tsunamayo** [tsunamayo/Starship-EVO#3874]
A new RGB controller gate has been added to the brick roaster.
Use it to control the color and brightness over time on light and glow bricks.

Feature:
- Up to 4 colors
- duration tweak
- gain tweak: a higher gain will spend more time on the color and less inside transition.
- Loop or Ping pong.
- You can set the controller to be active or not with a simple switch.
- For now colors are RGB input, but a color wheel will be added.

This build also introduced some big change on the command system behind the scene.
This allows leveraging on the new data-oriented performance stack and will be used extensively in upcoming updates.

Bugfixes:
#3860 Game breaks on Quit To Title

**Comment by tsunamayo** [comment]
Build is up!

**Comment by tsunamayo** [comment]
I just repushed the build as there was a last minute issue with the new RGB controller. Thanks!

**Comment by timethatswasted** [comment]
Logic blocks stick to whatever block grid size you used last. If the last thing you placed was a 4m block and you switch to a logic block it will try and place them of the 4m grid. 

This gets annoying if you’ve locked your block size in the f1 menu to be above 1m. You then have to open f1 lower the min size to 1/4, place a 1/4 block and then you can place a logic block normally.

**Comment by Uncle-Ulty** [comment]
omg! This is so cool! I'm having some ideas!

But tsuna, could you please make something about link tool? It's kinda a nightmare to connect every piece of glowing tile to the origin rgb gate!

![image](https://user-images.githubusercontent.com/73253472/122647977-5a95c480-d0fd-11eb-8393-a732b7e16e81.png)

**Comment by ProPeach** [comment]
RGB!
https://youtu.be/3nWKuwl9lxU

**Comment by tsunamayo** [comment]
@timethatswasted this is annoying indeed, I will fix this asap!

**Comment by Jakeman6299** [comment]
I found a bug. I connected the RGB gate to a glowing block, goofed around for a bit, then when I decided I was done, I deleted the glowing brick. But when I deleted the glowing brick (it was still connected to the RGB) I couldn't place or delete bricks anymore.

When I tried restarting my game, the test platform I had built to test stuff was gone. Had to rebuild it all over again.

**Comment by tsunamayo** [comment]
@timethatswasted Issue fixed, I repushed the build. Thanks

**Comment by tsunamayo** [comment]
@jakeman6299, okay let me check that.

**Comment by tsunamayo** [comment]
@Jakeman6299 I forgot to update you, the bug should be fixed and already live (from 2h ago). Thanks

**Comment by pinesh** [comment]
This patch seems to have interfered with child entity spawning and loading, resulting in missing/relocated entities. made a separate bug post

**Comment by Jakeman6299** [comment]
> @Jakeman6299 I forgot to update you, the bug should be fixed and already live (from 2h ago). Thanks

@tsunamayo Is there a new snapshot? I'm still on 21w24a and the bug is still here. :/

**Comment by ultrak2k** [comment]
Does this work on weapons? If so, could it be implemented on them? Might be interesting to make rainbow beams
