### ISSUE TITLE
Light Flickering ... again :D 

### ISSUE THREAD

**Issue by BigBadKangaroo** [tsunamayo/Starship-EVO#5044]
Hi there,

Bug report #4704 and #4746 is back again in the latest experimental branch 22w50c.

It's the same bug that happens just the same way as back then.
No difference.

https://user-images.githubusercontent.com/81495956/221243261-dfead2c3-4619-4dff-8053-02d35d4af216.mp4

**Comment by Vincent14** [comment]
Same issue, only on the experimental branch on my side

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, sorry for the late reply, do you get this often? Thanks

**Comment by BigBadKangaroo** [comment]
@tsunamayo Hi, yes I get this quite a lot of times ... more noticeable in longer build sessions with either lots of different blueprints spawned in, or one larger blueprint where a lot of building and deleting happens

**Comment by BigBadKangaroo** [comment]
Here's a blueprint that's constantly plaqued by this bug and I can't get rid of it (it's the BP from the post) 
[KF-Hajota IV.zip](https://github.com/tsunamayo/Starship-EVO/files/12442960/KF-Hajota.IV.zip)

**Comment by tsunamayo** [comment]
@BigBadKangaroo Hi, sorry I cant reproduce that issue... Do you still get this? Thanks

**Comment by tsunamayo** [comment]
@BigBadKangaroo btw I spotted some other decal issue on your magnificent build, so I fixed those.

**Comment by BigBadKangaroo** [comment]
Hi there,

so I can still reproduce the bug with this exact BP from above!
https://github.com/tsunamayo/Starship-EVO/assets/81495956/46cef11d-1475-424d-9762-3b412463f99b

However: This problem seems to start with the ships engines, so I deleted all of the smaller thrusters placed inside the main engines (there were A LOT of small thrusters!) and now the light flickering is gone ... 
Might be that this bug could not only be caused by actual lights, but by thrusters too (when they're too cluttered) 

Before, with thrusters:
![20240102201656_1](https://github.com/tsunamayo/Starship-EVO/assets/81495956/dd260cca-4eb4-47de-bed7-9ddd61dc1898)
After, without thrusters:
![20240102201543_1](https://github.com/tsunamayo/Starship-EVO/assets/81495956/c83c5185-1e39-4e76-b514-08851f751a6d)
