### ISSUE TITLE
fuel on light cruise running out to quick

### ISSUE THREAD

**Issue by KINGrimson** [tsunamayo/Starship-EVO#5194]
### Short Description of the issue:
when flying in light cruise you can only fly 
a few seconds before stoping and it sais your out of fule
strangly sometimes it works other times it doesnt
### Steps to reproduce the issue:
spawn ship
get in ship and activate lightcruise
see it  stop after seconds 
...

### Environment
- Starship EVO version: 23w29d
- Graphics Card: NVIDIA GeForce RTX 3080

### Additional information:
[Player-prev.log](https://github.com/tsunamayo/Starship-EVO/files/12143047/Player-prev.log)

_(Screenshots, Videos, Error logs, Related issues)_

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\Save_Data\Blueprints\`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tjohnman** [comment]
I'm having this issue as well. See the blueprint attached. This is my first time building a ship, so I wasn't sure this wasn't my fault.
You can only engage lightcruise for a few seconds until it claims it has ran out of fuel. The first time I tried it, however, it said the lightcruise engine was not thrusting forwards.

[Ship 1.zip](https://github.com/tsunamayo/Starship-EVO/files/12338124/Ship.1.zip)

**Comment by tsunamayo** [comment]
@KINGrimson I think this issue was fixed a few weeks ago. Please tell if it is not the case!
Cheers

**Comment by tjohnman** [comment]
> @KINGrimson I think this issue was fixed a few weeks ago. Please tell if it is not the case! Cheers

@tsunamayo I can confirm this is still happening as of today. I just tested it using the Explorer MCSS ship. You enter light cruise, and sometimes it works fine. Other times, it stops, saying it has ran out of fuel. There's also another error saying the thrusters are not in forward position that appears randomly when travelling in light cruise, but I don't know if it's related.
