### ISSUE TITLE
[Survival beta - suggestion] Picking up blocks shouldn't "cancel" the block you're placing

### ISSUE THREAD

**Issue by asanagisae** [tsunamayo/Starship-EVO#5531]
### Short Description of the issue:
When placing an armor block by dragging, if you pick up another block from the same series, your current shape is "lost". This hampers your build experience when you are building quickly. This isn't an issue in creative mode (because you don't get materials back by destroying blocks), but it'll be an issue for survival when you start building quickly.

The blocks you pick up should not affect your current selection when you are already holding your mouse down and dragging to place a new block.

### Steps to reproduce the issue:
1. Place a block down nearby
2. Right-click to delete the block - the block's materials should begin flying to you for retrieval
3. Quickly left-click and drag to place and stretch a new block in a custom size (4x5 for example)
4. When the flying material reaches you, the shape of your selection (4x5) is lost
5. When you let go of left-click, you will place a single block at the cursor's position - definitely not your intention
6. Delete the unintended block - the material should begin flying back to you
7. Attempt to left-click and drag to place the shape you meant to place
8. When the flying material reaches you, the shape of your selection (4x5) is lost again
9. Repeat until you're frustrated 😆

### Environment
- Starship EVO version: 24w06b

### Additional information:
The issue:
https://github.com/tsunamayo/Starship-EVO/assets/10069469/9ce9d6ed-a3cc-4314-9887-cd2a432b8b16

How it'll actually be when you're trying to build:
https://github.com/tsunamayo/Starship-EVO/assets/10069469/743cfeb4-ecfa-40ab-9e46-39330bec8c8c

**Comment by tsunamayo** [comment]
@asanagisae Hi, I cant reproduce the issue in the current build 24w07a. Can you confirm issue is fixed? Or maybe I am doing something wrong. Thanks

**Comment by asanagisae** [comment]
The issue is still in 24w07a (tested just now). It's a timing thing. You have to start left-click-drag before the first material reaches you, and you have to be still holding left-click when you pick the material up. It's still behaving as in the videos from earlier.

You know how when you place a cube block, switch to wedge, place a wedge, then delete the cube block, the cube block material will automatically change your armor block selection to cube when you pick it up? It should be related to that feature.

https://github.com/tsunamayo/Starship-EVO/assets/10069469/faf191a2-d4c0-4064-ba15-4c781bf7d4d1

**Comment by tsunamayo** [comment]
@asanagisae Okay funny enough I cannot reproduce with one set of stone but can with another one. So we have a weird bug, I keep you posted!
