### ISSUE TITLE
Ships Spawned fall through floor of other builds

### ISSUE THREAD

**Issue by Three50freak** [tsunamayo/Starship-EVO#5571]
### Short Description of the issue:

...whenever i spawn an entity like a ship,  it falls to the floor and gets stuck in the floor.

### Steps to reproduce the issue:

...be on a station (has artificial gravity)
spawn a ship
it falls into (not all the way through) the floor and is stuck there

### Environment
- Starship EVO version: 24w08a
- Graphics Card:  1070

### Additional information:

_(Screenshots, Videos, Error logs, Related issues)_

Please also include the `Player.log` file. You can find the log file here: `%UserProfile%\AppData\LocalLow\Moonfire Entertainment\Starship EVO\`

If you issue concerns a particular design please include any blueprint that could help to reproduce the issue.
Blueprint folder is over at:
`
![20240222053055_1](https://github.com/tsunamayo/Starship-EVO/assets/144556131/0271ca64-ed67-49ba-b6ce-576741707870)
[Hover Forklift.zip](https://github.com/tsunamayo/Starship-EVO/files/14372692/Hover.Forklift.zip)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14372693/Player.log)
![20240222053051_1](https://github.com/tsunamayo/Starship-EVO/assets/144556131/8f111182-7acd-44b2-82d7-bacaca08284c)`
You will need to zip the folder to upload it. 
To do so Right click and choose [Send to -> compressed zip file] then drag the .zip onto your report to upload it.

**Comment by tsunamayo** [comment]
@Three50freak Hi, thanks, issue is fixed for 24w09a. Cheers

**Comment by Snakeyes81** [comment]
I still have this bug, can't spawn anything on a space station that it will clip through the floor
