### ISSUE TITLE
[early-access 24w10a] Tutorial Severe Errors

### ISSUE THREAD

**Issue by nulldusk-heavy-industries** [tsunamayo/Starship-EVO#5657]
### Short Description of the issue:

The tutorial has several complete blocker errors.
* If the Basic Building Training mission is accidentally cancelled then immediately restarted, the mission refuses to spawn the wedge block again.
* When placing e.g. thrusters on the Repair Pod ship, it can glitch into the floor, then fly out into space.

...

### Steps to reproduce the issue:

For the Basic Building Training mission:
* Create a new character.
* Proceed to the training platform.
* Select Basic Building Training.
* Cancel Basic Building Training then, without closing the mission window, start it again.

Expected behavior: Basic Building Training can be played as normal.
Observed behavior: Basic Building Training does not spawn the wedge block, blocking the player from completing it.

For the Repair Pod ship glitch:
* Create a new character.
* Proceed through the tutorial until taking the Technical Modules Repairs mission.
* Interact with the ship, place modules on it, etc.

Expected behavior: Ship stays in place, or at worst falls on one side.
Observed behavior: Various activities will inconsistently cause the ship to float into the floor and then physics-glitch itself into the void of space.

...

### Environment
- Starship EVO version: early-access 24w10a, main branch.
- Graphics Card: RTX 3060 Max-Q.

### Additional information:

[Player-prev.log](https://github.com/tsunamayo/
Starship-EVO/files/14549840/Player-prev.log)
[Player.log](https://github.com/tsunamayo/Starship-EVO/files/14549843/Player.log)

Player-prev is the first instance of the ship being ejected to the void, Player is the second and additionally includes the Basic Building Training mission error.

**Comment by tsunamayo** [comment]
@nulldusk-heavy-industries Hi, thanks for reporting the issue, can you tell me what are your FPS in game? You can activate the FPS meter in the F3 menu.
I can reproduce some sinking with low fps, I am investigating.

**Comment by tsunamayo** [comment]
@nulldusk-heavy-industries Hi, I fixed the ship sinking issue, I am pushing a build asap. Not sure if it was the issue you reported though...

**Comment by nulldusk-heavy-industries** [comment]
Hi,

I habitually keep my FPS at 30 for stability.

Thank you for the fix! I'll test it as soon as possible.

**Comment by nulldusk-heavy-industries** [comment]
The fix works perfectly for the ship clipping. The mission cancel/restart bug remains.
